#!/usr/bin/python
# add a suf to each input line

import getopt
import stat
import os
import sys
import string

SUF = ""
EXPRESSION = False
SEPARATOR = ""
SKIP_HEADER = False


short_options = "esSthv"
long_options = [
    "expression",
    "space",
    "skip-header" "tab",
    "help",
    "version",
]

try:
    options, positional_arguments = getopt.gnu_getopt(
        sys.argv[1:], short_options, long_options
    )
except getopt.GetoptError as error:
    print(f"suf: '-{error.opt}': Option not recognized")
    sys.exit(1)

for option in options:
    argument = option[1]
    option = option[0]

    if option == "-h" or option == "--help":
        print("Usage: suf [OPTION]... SUFFIX [FILE]")
        print("Add SUFFIX after each line of input")
        print()
        print("  -e, --expression     execute SUFFIX as a shell command for each line")
        print("  -s, --space          place a space between SUFFIX and each line")
        print("  -S, --skip-header    do not put SUFFIX on the first line of input")
        print("  -t, --tab            place a tab between SUFFIX and each line")
        print("  -h, --help           display this help and exit")
        print("  -v, --version        display version information and exit")
        print()
        print("For full documentation, try 'man suf'.")
        sys.exit(0)
    elif option == "-v" or option == "--version":
        print("suf (TextUtils) v1.0.0")
        print("Copyright (C) 2024 HobbitJack.")
        print(
            "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
        )
        print("This is free software: you are free to change and redistribute it.")
        print("There is NO WARRANTY, to the extent permitted by law.")
        print()
        print("Written by HobbitJack.")
        sys.exit(0)
    elif option == "-e" or option == "--expression":
        EXPRESSION = True
    elif option == "-s" or option == "--space":
        SEPARATOR = " "
    elif option == "-S" or option == "--skip-header":
        SKIP_HEADER = True
    elif option == "-t" or option == "--tab":
        SEPARATOR = "\t"

if not positional_arguments or len(positional_arguments) == 1:
    if stat.S_ISFIFO(os.fstat(0).st_mode):
        input_file = "-"
    else:
        print("suf: Missing operand")
        sys.exit(1)
    if positional_arguments:
        SUF = positional_arguments[0]
else:
    if len(positional_arguments) > 2:
        print("suf: Too many arguments")
        sys.exit(1)
    SUF = positional_arguments[0]
    input_file = positional_arguments[1]

if input_file == "-":
    all_lines = sys.stdin.read().splitlines()
else:
    if os.path.isfile(input_file):
        pass
    elif os.path.isfile(f"{os.getcwd}/{input_file}"):
        input_file = f"{os.getcwd}/{input_file}"
    elif os.path.isdir(input_file) or os.path.isdir(f"{os.getcwd}/{input_file}"):
        print(f"suf: {input_file}: Is a directory")
        sys.exit(1)
    else:
        print(f"suf: {input_file}: No such file or directory")
        sys.exit(1)

    with open(input_file, mode="r", encoding="utf8") as text_file:
        all_lines = text_file.read().splitlines()

for line in all_lines:
    if SKIP_HEADER:
        SKIP_HEADER = False
        print(line)
        continue
    if EXPRESSION:
        os.environ["LINE"] = line
        print(f"{line}{SEPARATOR}{os.popen(SUF).read()[:-1]}")
        os.environ["LINE"] = ""
        continue
    print(f"{line}{SEPARATOR}{SUF}")
