#!/usr/bin/python
# template program for extra textutils

import getopt
import stat
import os
import sys

SEPARATOR = "\t"

short_options = "s:hv"
long_options = [
    "separator=",
    "help",
    "version",
]

try:
    options, positional_arguments = getopt.gnu_getopt(
        sys.argv[1:], short_options, long_options
    )
except getopt.GetoptError as error:
    print(f"TOOL_NAME: '-{error.opt}': Option not recognized", file=sys.stderr)
    sys.exit(1)

for option in options:
    argument = option[1]
    option = option[0]

    if option == "-h" or option == "--help":
        print("Usage: TOOL_NAME [OPTION]... [FILE]")
        print("Does important things")
        print()
        print(
            "  -s, --separator=SEPARATOR    use SEPARATOR instead of tab to separate fields"
        )
        print("  -h, --help                   display this help and exit")
        print("  -v, --version                display version information and exit")
        print()
        print("For full documentation, try 'man TOOL_NAME'.")
        sys.exit(0)
    elif option == "-v" or option == "--version":
        print("TOOL_NAME (Extra Textutils) v1.0.0")
        print("Copyright (C) 2024-2025 HobbitJack.")
        print(
            "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
        )
        print("This is free software: you are free to change and redistribute it.")
        print("There is NO WARRANTY, to the extent permitted by law.")
        print()
        print("Written by HobbitJack.")
        sys.exit(0)
    elif option == "-s" or option == "--separator":
        SEPARATOR = argument

if stat.S_ISFIFO(os.fstat(0).st_mode):
    input_file = "-"
else:
    if not len(positional_arguments):
        print(f"TOOL_NAME: Missing operand", file=sys.stderr)
        sys.exit(1)

    input_file = positional_arguments.pop(
        0
    )  # Either use or don't use 0 here (if has multiple types of positional arguments)

if positional_arguments:
    print(f"TOOL_NAME: '{positional_arguments[0]}': Extra operand", file=sys.stderr)
    sys.exit(1)

if input_file == "-":
    all_lines = sys.stdin.read().splitlines()
else:
    if os.path.isfile(input_file):
        pass
    elif os.path.isfile(f"{os.getcwd}/{input_file}"):
        input_file = f"{os.getcwd}/{input_file}"
    elif os.path.isdir(input_file) or os.path.isdir(f"{os.getcwd}/{input_file}"):
        print(f"TOOL_NAME: {input_file}: Is a directory", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"TOOL_NAME: {input_file}: No such file or directory", file=sys.stderr)
        sys.exit(1)

    with open(input_file, mode="r", encoding="utf8") as text_file:
        all_lines = text_file.read().splitlines()
